image: clever/drone-node:6.2.2
publish:
  npm:
    token: $$npm_token
    when:
      branch: master
  s3:
    access_key: $$aws_access_key_id
    bucket: "assets.clever.com"
    recursive: true
    region: us-east-1
    secret_key: $$aws_secret_access_key_id
    source: dist/css/
    target: /design/
    when:
      branch: master
script:
- ./test_drone.sh
