image: node0.10
publish:
   npm:
     email: $$npm_drone_email
     password: $$npm_drone_password
     registry: https://registry.npmjs.org
     username: $$npm_drone_username
     when:
       branch: master
script:
- nvm install v5.7.1 &> /dev/null
