extends: "airbnb"
env:
  mocha: true
  jest: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
plugins:
  - "react"
  - "@typescript-eslint"
settings:
  import/resolver: webpack
rules:
  # no hard limit on line length
  max-len: 0

  # we allow use of console...for now
  no-console: 0

  # we currently use snake case in most places, however, we'd like to switch to camelCase eventually since it's more common in the JS community
  camelcase: 0

  # vars are necessary for server-side requires right now
  no-var: 0
  vars-on-top: 0

  # multi spaces only allowed for aligning variable/import declarations
  no-multi-spaces:
    - 2
    - exceptions:
        VariableDeclarator: true
        ImportDeclaration: true

  # we currently use null in many places, so allow == for null checks
  eqeqeq:
    - 2
    - "smart"

  quotes: [2, "double", "avoid-escape"]
  new-cap:
    - 2
    - newIsCapExceptions: ["kayvee.logger"]
  no-param-reassign:
    - 2
    - props: false
  key-spacing:
    - 2
    - mode: "minimum"

  # Allow functions and classes to be declared after they are referenced.
  # This enables us to define more important public functions/classes toward the top of a file and
  # less relevant private helpers below.
  no-use-before-define:
    - 2
    - classes: false
      functions: false

  react/jsx-curly-spacing:
    - 2
    - "never"

  prefer-const: ["error", { "destructuring": "all" }]

  indent:
    - off

  # This is handled by the "@typescript-eslint/parser"
  no-unused-vars:
    - off
