apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: components
  description: Frontend components
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
