import React from "react";

const Hello = {
  AD: { country: "Andorra", hello: "Hola" },
  AE: { country: "United Arab Emirates", hello: "Marhaba" },
  AF: { country: "Afghanistan", hello: "Senga yai" },
  AG: { country: "Antigua and Barbuda", hello: "Hello" },
  AI: { country: "Anguilla", hello: "Hello" },
  AL: { country: "Albania", hello: "Tungjatjeta" },
  AM: { country: "Armenia", hello: "Barev" },
  AN: { country: "Netherlands Antilles", hello: "Kon ta bai" },
  AO: { country: "Angola", hello: "Olá" },
  AP: { country: "Asia/Pacific Region", hello: "Hello" },
  AQ: { country: "Antarctica", hello: "Hello" },
  AR: { country: "Argentina", hello: "Hola" },
  AS: { country: "American Samoa", hello: "Hello" },
  AT: { country: "Austria", hello: "Hallo" },
  AU: { country: "Australia", hello: "Hello" },
  AW: { country: "Aruba", hello: "Kon ta bai" },
  AX: { country: "Aland Islands", hello: "Hello" },
  AZ: { country: "Azerbaijan", hello: "Salam" },
  BA: { country: "Bosnia and Herzegovina", hello: "Zdravo" },
  BB: { country: "Barbados", hello: "Hello" },
  BD: { country: "Bangladesh", hello: "Namaskar" },
  BE: { country: "Belgium", hello: "Hallo" },
  BF: { country: "Burkina Faso", hello: "Bonjour" },
  BG: { country: "Bulgaria", hello: "Zdravei" },
  BH: { country: "Bahrain", hello: "Marhaba" },
  BI: { country: "Burundi", hello: "Bonjour" },
  BJ: { country: "Benin", hello: "Bonjour" },
  BM: { country: "Bermuda", hello: "Hello" },
  BN: { country: "Brunei Darussalam", hello: "Selamat" },
  BO: { country: "Bolivia", hello: "Hola" },
  BR: { country: "Brazil", hello: "Olá" },
  BS: { country: "Bahamas", hello: "Hello" },
  BT: { country: "Bhutan", hello: "Kuzu zangpo" },
  BV: { country: "Bouvet Island", hello: "Hello" },
  BW: { country: "Botswana", hello: "Dumela" },
  BY: { country: "Belarus", hello: "Вітаю" },
  BZ: { country: "Belize", hello: "Hello" },
  CA: { country: "Canada", hello: "Hello" },
  CD: { country: "Congo  The Democratic Republic of the", hello: "Bonjour" },
  CF: { country: "Central African Republic", hello: "Bonjour" },
  CG: { country: "Congo", hello: "Bonjour" },
  CH: { country: "Switzerland", hello: "Hallo" },
  CI: { country: "Cote d''Ivoire", hello: "Bonjour" },
  CK: { country: "Cook Islands", hello: "Kia orana" },
  CL: { country: "Chile", hello: "Hola" },
  CM: { country: "Cameroon", hello: "Hello" },
  CN: { country: "China", hello: <span>&#20320;&#22909;</span> },
  CO: { country: "Colombia", hello: "Hola" },
  CR: { country: "Costa Rica", hello: "Hola" },
  CU: { country: "Cuba", hello: "Hola" },
  CV: { country: "Cape Verde", hello: "Olá" },
  CY: { country: "Cyprus", hello: <span>&#915;&#949;&#953;&#945; &#963;&#959;&#965;</span> },
  CZ: { country: "Czech Republic", hello: "Dobrý den" },
  DE: { country: "Germany", hello: "Hallo" },
  DJ: { country: "Djibouti", hello: "Marhaba" },
  DK: { country: "Denmark", hello: "Hej" },
  DM: { country: "Dominica", hello: "Hello" },
  DO: { country: "Dominican Republic", hello: "Hola" },
  DZ: { country: "Algeria", hello: "Marhaba" },
  EC: { country: "Ecuador", hello: "Hola" },
  EE: { country: "Estonia", hello: "Tervist" },
  EG: { country: "Egypt", hello: "Marhaba" },
  ER: { country: "Eritrea", hello: "Marhaba" },
  ES: { country: "Spain", hello: "Hola" },
  ET: { country: "Ethiopia", hello: "Teanastëllën" },
  EU: { country: "Europe", hello: "Hello" },
  FI: { country: "Finland", hello: "Moi" },
  FJ: { country: "Fiji", hello: "Hello" },
  FK: { country: "Falkland Islands (Malvinas)", hello: "Hello" },
  FM: { country: "Micronesia  Federated States of", hello: "Hello" },
  FO: { country: "Faroe Islands", hello: "Hallo" },
  FR: { country: "France", hello: "Bonjour" },
  GA: { country: "Gabon", hello: "Bonjour" },
  GB: { country: "Great Britain", hello: "Hello" },
  GD: { country: "Grenada", hello: "Hello" },
  GE: { country: "Georgia", hello: "Gamardjobat" },
  GF: { country: "French Guiana", hello: "Bonjour" },
  GG: { country: "Guernsey", hello: "Hello" },
  GH: { country: "Ghana", hello: "Hello" },
  GI: { country: "Gibraltar", hello: "Hello" },
  GL: { country: "Greenland", hello: "Aluu" },
  GM: { country: "Gambia", hello: "Hello" },
  GN: { country: "Guinea", hello: "Bonjour" },
  GP: { country: "Guadeloupe", hello: "Hello" },
  GQ: { country: "Equatorial Guinea", hello: "Hola" },
  GR: { country: "Greece", hello: <span>&#915;&#949;&#953;&#945; &#963;&#959;&#965;</span> },
  GT: { country: "Guatemala", hello: "Hola" },
  GU: { country: "Guam", hello: "Hello" },
  GW: { country: "Guinea-Bissau", hello: "Olá" },
  GY: { country: "Guyana", hello: "Hello" },
  HK: { country: "Hong Kong", hello: <span>&#20320;&#22909;</span> },
  HN: { country: "Honduras", hello: "HHola" },
  HR: { country: "Croatia", hello: "Bok" },
  HT: { country: "Haiti", hello: "Bonjour" },
  HU: { country: "Hungary", hello: "Jó napot" },
  ID: { country: "Indonesia", hello: "Selamat" },
  IE: { country: "Ireland", hello: "Haileo" },
  IL: { country: "Israel", hello: "Shalom" },
  IM: { country: "Isle of Man", hello: "Hello" },
  IN: { country: "India", hello: <span>&#2344;&#2350;&#2360;&#2381;&#2340;&#2375;</span> },
  IO: { country: "British Indian Ocean Territory", hello: "Hello" },
  IQ: { country: "Iraq", hello: "Marhaba" },
  IR: { country: "Iran  Islamic Republic of", hello: "Salâm" },
  IS: { country: "Iceland", hello: "Góðan daginn" },
  IT: { country: "Italy", hello: "Buon giorno" },
  JE: { country: "Jersey", hello: "Hello" },
  JM: { country: "Jamaica", hello: "Hello" },
  JO: { country: "Jordan", hello: "Marhaba" },
  JP: { country: "Japan", hello: <span>&#12371;&#12435;&#12395;&#12385;&#12399;</span> },
  KE: { country: "Kenya", hello: "Habari" },
  KG: { country: "Kyrgyzstan", hello: "Kandisiz" },
  KH: { country: "Cambodia", hello: "Sua s''dei" },
  KI: { country: "Kiribati", hello: "Mauri" },
  KM: { country: "Comoros", hello: "Bariza djioni" },
  KN: { country: "Saint Kitts and Nevis", hello: "Hello" },
  KP: {
    country: "Korea  Democratic People''s Republic of",
    hello: <span>&#50504;&#45397;&#54616;&#49464;&#50836;</span>,
  },
  KR: {
    country: "Korea  Republic of",
    hello: <span>&#50504;&#45397;&#54616;&#49464;&#50836;</span>,
  },
  KW: { country: "Kuwait", hello: "Marhaba" },
  KY: { country: "Cayman Islands", hello: "Hello" },
  KZ: { country: "Kazakhstan", hello: "Salam" },
  LA: { country: "Lao People''s Democratic Republic", hello: "Sabaidee" },
  LB: { country: "Lebanon", hello: "Marhaba" },
  LC: { country: "Saint Lucia", hello: "Hello" },
  LI: { country: "Liechtenstein", hello: "Hallo" },
  LK: { country: "Sri Lanka", hello: "A`yubowan" },
  LR: { country: "Liberia", hello: "Hello" },
  LS: { country: "Lesotho", hello: "Hello" },
  LT: { country: "Lithuania", hello: "Laba diena" },
  LU: { country: "Luxembourg", hello: "Moïen" },
  LV: { country: "Latvia", hello: "Sveiki" },
  LY: { country: "Libyan Arab Jamahiriya", hello: "Marhaba" },
  MA: { country: "Morocco", hello: "Marhaba" },
  MC: { country: "Monaco", hello: "Bonjour" },
  MD: { country: "Moldova  Republic of", hello: "Salut" },
  ME: { country: "Montenegro", hello: "Zdravo" },
  MG: { country: "Madagascar", hello: "Manao ahoana" },
  MH: { country: "Marshall Islands", hello: "Yokwe" },
  MK: { country: "Macedonia", hello: <span>&#1047;&#1076;&#1088;&#1072;&#1074;&#1086;</span> },
  ML: { country: "Mali", hello: "Bonjour" },
  MM: { country: "Myanmar", hello: "Mingalarba" },
  MN: { country: "Mongolia", hello: "Sain baina uu" },
  MO: { country: "Macao", hello: <span>&#20320;&#22909;</span> },
  MP: { country: "Northern Mariana Islands", hello: "Hello" },
  MQ: { country: "Martinique", hello: "Hello" },
  MR: { country: "Mauritania", hello: "Marhaba" },
  MS: { country: "Montserrat", hello: "Hello" },
  MT: { country: "Malta", hello: "Bongu" },
  MU: { country: "Mauritius", hello: "Hello" },
  MV: { country: "Maldives", hello: "Kihineth" },
  MW: { country: "Malawi", hello: "Muribwanji" },
  MX: { country: "Mexico", hello: "Hola" },
  MY: { country: "Malaysia", hello: "Selamat" },
  MZ: { country: "Mozambique", hello: "Olá" },
  NA: { country: "Namibia", hello: "Hello" },
  NC: { country: "New Caledonia", hello: "Bozo" },
  NE: { country: "Niger", hello: "Bonjour" },
  NF: { country: "Norfolk Island", hello: "Whataway" },
  NG: { country: "Nigeria", hello: "Hello" },
  NI: { country: "Nicaragua", hello: "Hola" },
  NL: { country: "Netherlands", hello: "Hallo" },
  NO: { country: "Norway", hello: "Hallo" },
  NP: { country: "Nepal", hello: "Namaste" },
  NR: { country: "Nauru", hello: "Hello" },
  NU: { country: "Niue", hello: "Faka lofa lahi atu" },
  NZ: { country: "New Zealand", hello: "Hello" },
  OM: { country: "Oman", hello: "Marhaba" },
  PA: { country: "Panama", hello: "Hola" },
  PE: { country: "Peru", hello: "Hola" },
  PF: { country: "French Polynesia", hello: "Bonjour" },
  PG: { country: "Papua New Guinea", hello: "Hello" },
  PH: { country: "Philippines", hello: "Halo" },
  PK: { country: "Pakistan", hello: "Adaab" },
  PL: { country: "Poland", hello: "Dzień dobry" },
  PM: { country: "Saint Pierre and Miquelon", hello: "Hello" },
  PR: { country: "Puerto Rico", hello: "Hola" },
  PS: { country: "Palestinian Territory", hello: "Marhaba" },
  PT: { country: "Portugal", hello: "Olá" },
  PW: { country: "Palau", hello: "Alii" },
  PY: { country: "Paraguay", hello: "Hola" },
  QA: { country: "Qatar", hello: "Marhaba" },
  RE: { country: "Reunion", hello: "Hello" },
  RO: { country: "Romania", hello: "Salut" },
  RS: { country: "Serbia", hello: "Zdravo" },
  RU: {
    country: "Russian Federation",
    hello: (
      <span>
        &#1047;&#1076;&#1088;&#1072;&#1074;&#1089;&#1090;&#1074;&#1091;&#1081;&#1090;&#1077;
      </span>
    ),
  },
  RW: { country: "Rwanda", hello: "Hello" },
  SA: { country: "Saudi Arabia", hello: "Marhaba" },
  SB: { country: "Solomon Islands", hello: "Hello" },
  SC: { country: "Seychelles", hello: "Hello" },
  SD: { country: "Sudan", hello: "Marhaba" },
  SE: { country: "Sweden", hello: "God dag" },
  SG: { country: "Singapore", hello: "Selamat" },
  SI: { country: "Slovenia", hello: "Živijo" },
  SK: { country: "Slovakia", hello: "Dobrý deň" },
  SL: { country: "Sierra Leone", hello: "Hello" },
  SM: { country: "San Marino", hello: "Buon giorno" },
  SN: { country: "Senegal", hello: "Bonjour" },
  SO: { country: "Somalia", hello: "Maalim wanaqsan" },
  SR: { country: "Suriname", hello: "Hallo" },
  ST: { country: "Sao Tome and Principe", hello: "Hello" },
  SV: { country: "El Salvador", hello: "Hola" },
  SY: { country: "Syrian Arab Republic", hello: "Marhaba" },
  SZ: { country: "Swaziland", hello: "Hello" },
  TC: { country: "Turks and Caicos Islands", hello: "Hello" },
  TD: { country: "Chad", hello: "Marhaba" },
  TG: { country: "Togo", hello: "Bonjour" },
  TH: { country: "Thailand", hello: "Sawatdi" },
  TJ: { country: "Tajikistan", hello: "Salom" },
  TK: { country: "Tokelau", hello: "Taloha" },
  TM: { country: "Turkmenistan", hello: "Salam" },
  TN: { country: "Tunisia", hello: "Marhaba" },
  TO: { country: "Tonga", hello: "Malo e lelei" },
  TR: { country: "Turkey", hello: "Merhaba" },
  TT: { country: "Trinidad and Tobago", hello: "Hello" },
  TV: { country: "Tuvalu", hello: "Talofa" },
  TW: { country: "Taiwan", hello: <span>&#20320;&#22909;</span> },
  TZ: { country: "Tanzania  United Republic of", hello: "Habari" },
  UA: { country: "Ukraine", hello: "Pryvit" },
  UG: { country: "Uganda", hello: "Habari" },
  UK: { country: "United Kingdom", hello: "Hello" },
  UM: { country: "United States Minor Outlying Islands", hello: "Hello" },
  US: { country: "United States", hello: "Hello" },
  UY: { country: "Uruguay", hello: "Hola" },
  UZ: { country: "Uzbekistan", hello: "Salom" },
  VA: { country: "Holy See (Vatican City State)", hello: "Buon giorno" },
  VC: { country: "Saint Vincent and the Grenadines", hello: "Hello" },
  VE: { country: "Venezuela", hello: "Hola" },
  VG: { country: "Virgin Islands  British", hello: "Hello" },
  VI: { country: "Virgin Islands  U.S.", hello: "Hello" },
  VN: { country: "Vietnam", hello: "Chào" },
  VU: { country: "Vanuatu", hello: "Halo" },
  WF: { country: "Wallis and Futuna", hello: "Malo le kataki" },
  WS: { country: "Samoa", hello: "Talofa" },
  YE: { country: "Yemen", hello: "Marhaba" },
  YT: { country: "Mayotte", hello: "Hello" },
  ZA: { country: "South Africa", hello: "Hello" },
  ZM: { country: "Zambia", hello: "Hello" },
  ZW: { country: "Zimbabwe", hello: "Hello" },
};

export default Hello;
